### ISSUE TITLE
NOT_RECEIVED error when running StarkNet.js workshop with starknet-devnet

### ISSUE THREAD

**Issue by anders-torbjornsen** [0xs34n/starknet.js#182]
The StarkNet.js workshop example works fine on testnet, but when running it against starknet-devnet I get this error:
```Reading Argent Account Contract...
Reading ERC20 Contract...
Deployment Tx - Account Contract to StarkNet...
Waiting for Tx to be Accepted on Starknet - Argent Account Deployment...
Invoke Tx - Initialize Argnet Account...
Waiting for Tx to be Accepted on Starknet - Initialize Account...
/home/anders/starknet.js-workshop/node_modules/starknet/dist/provider/default.js:449
                            error = new Error(message);
                                    ^

Error: NOT_RECEIVED
    at Provider.<anonymous> (/home/anders/starknet.js-workshop/node_modules/starknet/dist/provider/default.js:449:37)
    at step (/home/anders/starknet.js-workshop/node_modules/starknet/dist/provider/default.js:44:23)
    at Object.next (/home/anders/starknet.js-workshop/node_modules/starknet/dist/provider/default.js:25:53)
    at fulfilled (/home/anders/starknet.js-workshop/node_modules/starknet/dist/provider/default.js:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  response: { tx_status: 'NOT_RECEIVED' }
}```

**Comment by anders-torbjornsen** [comment]
Turns out I'm just an idiot and I forgot to pass in my provider to the contract
