### ISSUE TITLE
strm.avail_in = strm.input.length;

### ISSUE THREAD

**Issue by tolerant-hu** [0xs34n/starknet.js#584]
node : v18.16.0
pkg:  "starknet": "^4.22.0"

#### Code 
```ts
import * as fs from 'fs';
import { Account, ec, Provider } from "starknet";
import { Contract, json } from "starknet";
import * as dotenv from "dotenv";
dotenv.config();

const provider = new Provider({
  sequencer: {
    baseUrl: 'https://alpha4.starknet.io',
    feederGatewayUrl: 'feeder_gateway',
    gatewayUrl: 'gateway',
  }
})

const privateKey = process.env.ACCOUNT_PRIVKEY;
const starkKeyPair = ec.getKeyPair(privateKey);
const accountAddress = "xxxxxx";

const account = new Account(provider, accountAddress, starkKeyPair);

const testClassHash = "xxxxx";
const compiledTest = json.parse(fs.readFileSync("xxxxx.json").toString("ascii"));

async function main() {
    const deployResponse = await account.declareDeploy({ contract: compiledTest, classHash: testClassHash });
    console.log(deployResponse);
}


main()
```
#### Error 
file:///opt/test_sk/node_modules/pako/dist/pako.esm.mjs:3942
  strm.avail_in = strm.input.length;
                             ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Deflate$1.push (file:///opt/test_sk/node_modules/pako/dist/pako.esm.mjs:3942:30)
    at deflate$1 (file:///opt/test_sk/node_modules/pako/dist/pako.esm.mjs:4058:12)
    at gzip$1 (file:///opt/test_sk/node_modules/pako/dist/pako.esm.mjs:4093:10)
    at compressProgram (file:///opt/test_sk/node_modules/starknet/dist/index.mjs:2505:29)
    at parseContract (file:///opt/test_sk/node_modules/starknet/dist/index.mjs:2556:14)
    at Account.buildDeclarePayload (file:///opt/test_sk/node_modules/starknet/dist/index.mjs:4998:32)
    at Account.estimateDeclareFee (file:///opt/test_sk/node_modules/starknet/dist/index.mjs:4690:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Account.getSuggestedMaxFee (file:///opt/test_sk/node_modules/starknet/dist/index.mjs:4983:23)
    at async Account.declare (file:///opt/test_sk/node_modules/starknet/dist/index.mjs:4836:49)

**Comment by tabaktoni** [comment]
@tolerant-hu Closing issue due to inactivity.
If you still encounter the same issue please reopen it again.
