### ISSUE TITLE
Cannot call swap function on 10KSwap contract

### ISSUE THREAD

**Issue by tomasz90** [0xs34n/starknet.js#585]
I am trying to swap tokens on 10KSwap contract using starknetjs, but without success.
I am constantly getting error that `path` argument is not an array(see below). 
Path that I am passing is for instance:
```
const path = ['0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7',
    '0x3fe2b97c1fd336e750087d68b9b867997fd64a2661ff3ca5a7c771641e8e7ac']
```
I tried to debug this, but I couldn't pin breakpoint.
contract that I am calling is: https://starkscan.co/contract/0x07a6f98c03379b9513ca84cca1373ff452a7462a3b61598f0af5bb27ad7f76d1
I am not sure is this problem on my side not understanding library and types that I should pass to function or there is some bug in library??

Below is my function:

```
async swapExactTokensForTokens(
        signer: Account,
        _amount: BigNumberish,
        _minAmountOut: BigNumberish,
        pathLen: number,
        path: Array<string>
    ) {
        this.contract.connect(signer)
        const amount = uint256.bnToUint256(_amount)
        const minAmountOut = uint256.bnToUint256(_minAmountOut)
        const deadline = this.getDeadline5min()
        const tx = await this.contract.swapExactTokensForTokens(
            amount,
            minAmountOut,
            pathLen,
            path,
            signer.address,
            deadline
        )
        console.log(`swapExactTokensForTokens txhash: ${tx.transaction_hash}`)
        await this.contract.providerOrAccount.waitForTransaction(tx.transaction_hash)
    }
```

And the error:

```
/Users/tomasz/WebstormProjects/starknet/node_modules/minimalistic-assert/index.js:5
    throw new Error(msg || 'Assertion failed');
          ^
Error: arg path should be an Array
    at assert (/Users/tomasz/WebstormProjects/starknet/node_modules/minimalistic-assert/index.js:5:11)
    at /Users/tomasz/WebstormProjects/starknet/node_modules/starknet/src/utils/calldata.ts:111:9
    at Array.forEach (<anonymous>)
    at CheckCallData.validateMethodAndArgs (/Users/tomasz/WebstormProjects/starknet/node_modules/starknet/src/utils/calldata.ts:82:22)
    at Contract.invoke (/Users/tomasz/WebstormProjects/starknet/node_modules/starknet/src/contract/default.ts:271:24)
    at Contract.swapExactTokensForTokens (/Users/tomasz/WebstormProjects/starknet/node_modules/starknet/src/contract/default.ts:68:21)
    at _10KSwap.<anonymous> (/Users/tomasz/WebstormProjects/starknet/typescript/contracts/10KSwap.ts:16:40)
    at Generator.next (<anonymous>)
    at /Users/tomasz/WebstormProjects/starknet/typescript/contracts/10KSwap.ts:8:71
    at new Promise (<anonymous>)
```

**Comment by tabaktoni** [comment]
Hello @tomasz90, thank you for reposting.
As the bug template is ignored, I need to ask you questions to reproduce this:
In what env do you run this? If Node then what version?
**What version of starknet.js do you use?**

**Regarding provided code:**
How did you create the Contract class, can you provide an example?
``` ts
this.contract
```

It looks like the parameters are not matching, I'll try to test this but I need starknetjs version you use.

**Comment by tomasz90** [comment]
Contract is beeing created via provider: 

`await provider.getClassAt(address)`

I figured out what was going on, but don't understand why this works that way.
I I removed pathLen paramater from:

```
const tx = await this.contract.swapExactTokensForTokens(
            amount,
            minAmountOut,
            pathLen,
            path,
            signer.address,
            deadline
        )
```

Then I was able to make transaction. But on cairo file I see that path lenght is included. Unfortunately I couldnt find any info in docs that length of arrays should not be included.

**Comment by Kron1749** [comment]
you don't need to pass pathLen,so it should be 

const tx = await this.contract.swapExactTokensForTokens(
            amount,
            minAmountOut,
            path,
            signer.address,
            deadline
        )

**Comment by tabaktoni** [comment]
Issue resolved.
@thecotne Please consider contributing to the documentation so we can have it better.
Thank you.
