### ISSUE TITLE
AssertionError: assert_not_zero failed: 0 = 0 when transferring ERC20

### ISSUE THREAD

**Issue by tomasz90** [0xs34n/starknet.js#586]
I am trying to transfer ERC20 token, but without success. I am constantly getting the following error:

```
Traceback (most recent call last):
  File "<hint1>", line 3, in <module>
AssertionError: assert_not_zero failed: 0 = 0.
    at SequencerProvider.waitForTransaction (/Users/tomasz/WebstormProjects/starknet/node_modules/starknet/src/provider/sequencer.ts:516:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  response: [Object: null prototype] {
    tx_status: 'REJECTED',
    tx_failure_reason: [Object: null prototype] {
      code: 'TRANSACTION_FAILED',
      error_message: 'Error at pc=0:12:\n' +
        'Got an exception while executing a hint.\n' +
        'Cairo traceback (most recent call last):\n' +
        'Unknown location (pc=0:161)\n' +
        'Unknown location (pc=0:147)\n' +
        '\n' +
        'Error in the called contract (0x43a856be6c512c9052ffa394bb6410c98c298a28f6617fd517ef85f91369bb0):\n' +
        'Error at pc=0:39:\n' +
        'Got an exception while executing a hint.\n' +
        'Cairo traceback (most recent call last):\n' +
        'Unknown location (pc=0:1398)\n' +
        'Unknown location (pc=0:1351)\n' +
        'Unknown location (pc=0:569)\n' +
        'Error message: argent: multicall 0 failed\n' +
        'Unknown location (pc=0:586)\n' +
        '\n' +
        'Error in the called contract (0x10884171baf1914edc28d7afb619b40a4051cfae78a094a55d230f19e944a28):\n' +
        'Error at pc=0:10:\n' +
        'Got an exception while executing a hint.\n' +
        'Cairo traceback (most recent call last):\n' +
        'Unknown location (pc=0:371)\n' +
        'Unknown location (pc=0:357)\n' +
        '\n' +
        'Error in the called contract (0x10884171baf1914edc28d7afb619b40a4051cfae78a094a55d230f19e944a28):\n' +
        'Error at pc=0:222:\n' +
        'Got an exception while executing a hint.\n' +
        'Cairo traceback (most recent call last):\n' +
        'Unknown location (pc=0:2960)\n' +
        'Unknown location (pc=0:2935)\n' +
        'Unknown location (pc=0:2047)\n' +
        'Unknown location (pc=0:2102)\n' +
        'Unknown location (pc=0:986)\n' +
        '\n' +
        'Error in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):\n' +
        'Error at pc=0:104:\n' +
        'Got an exception while executing a hint.\n' +
        'Cairo traceback (most recent call last):\n' +
        'Unknown location (pc=0:1678)\n' +
        'Unknown location (pc=0:1664)\n' +
        '\n' +
        'Error in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):\n' +
        'Error at pc=0:9:\n' +
        'Got an exception while executing a hint.\n' +
        'Cairo traceback (most recent call last):\n' +
        'Unknown location (pc=0:1434)\n' +
        'Unknown location (pc=0:1386)\n' +
        '\n' +
        'Traceback (most recent call last):\n' +
        '  File "<hint1>", line 3, in <module>\n' +
        'AssertionError: assert_not_zero failed: 0 = 0.'
    }
  }
}
```

Here is my function which I wrote:
```
public async transfer(signer:Account, to: string, _amount: BigNumberish) {
        this.contract.connect(signer)
        const amount = uint256.bnToUint256(_amount)
        const tx = await this.contract.transfer(to, amount, { maxFee: 1000000000000000} )

        console.log(`approve txhash: ${tx.transaction_hash}`)
        await this.contract.providerOrAccount.waitForTransaction(tx.transaction_hash)
    }
```

starknet version: 4.4.2
node: 19.7

**Comment by tomasz90** [comment]
Ok, I figured out what was going on, here is the explanation for anyone that will encounter this issue:

ETH has two contracts: main and proxy. I was calling main contract which is: 0x048624e084dc68d82076582219c7ed8cb0910c01746cca3cd72a28ecfe07e42d
But you have to call proxy contract:
0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7
with abi get from main contract.

There could be some improvement in starknetjs when calling: provider.getClassAt(abiSource)
It could predict that contract is only proxy and return not only proxy functions but also functions from contract behind proxy.
