### ISSUE TITLE
Calling `array2d_array` with `call` fail with `Error: Invalid number of arguments`

### ISSUE THREAD

**Issue by haroune-mohammedi** [0xs34n/starknet.js#647]
**Describe the bug**
Calling `array2d_array` with `call` (see below for reproduction) fail with the following error but works just file if called with meta-class functions  i.e `contract.array2d_array`

```
/Users/mac/Workspace/abiwan-tutorial/node_modules/starknet/dist/index.js:3186
      throw Error(
            ^

Error: Invalid number of arguments, expected 1 arguments, but got 2
    at CallData.validate (/Users/mac/Workspace/abiwan-tutorial/node_modules/starknet/dist/index.js:3186:13)
    at /Users/mac/Workspace/abiwan-tutorial/node_modules/starknet/dist/index.js:6185:23
    at getCalldata (/Users/mac/Workspace/abiwan-tutorial/node_modules/starknet/dist/index.js:6104:10)
    at Contract.call (/Users/mac/Workspace/abiwan-tutorial/node_modules/starknet/dist/index.js:6183:22)
    at main (/Users/mac/Workspace/abiwan-tutorial/dist/example.js:14:68)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**To Reproduce**
```typescript
import { Provider, Contract, constants } from "starknet";

async function main() {
  const provider = new Provider({
    sequencer: { network: constants.NetworkName.SN_GOERLI2 },
  });

  const testAddress =
    "0x01c6b2a993b335cabc12dd5fa39875f456f07f23b10dcbdf6529667a322bbda4";
  const { abi: testAbi } = await provider.getClassAt(testAddress);

  if (testAbi === undefined) {
    throw new Error("No ABI.");
  }

  const myTestContract = new Contract(testAbi, testAddress, provider);

  console.log(
    "array2d_array meta-class =",
    await myTestContract.call("array2d_array", [
      [1n, 2n],
      [3n, 4n],
    ])
  );
}

main();
```

**Expected behavior**
The function call should not fail

**Screenshots**

**Desktop (please complete the following information):**

- Browser & version [e.g. chrome, safari, webworker]: No brower, I'm running the script from terminal
- Node version [e.g. 16.0.1]: v18.9.0
- Starknet.js version: I'm on branch `634-contract-class-types`, commit 1ec347a6ba02dbf6194f7208e09791cc49c2e77b
- Network [devnet, testnet]: testnet2

**Additional context**

**Comment by PhilippeR26** [comment]
This command :
```typescript
 await myTestContract.call("array2d_array", [
      [1n, 2n],
      [3n, 4n],
    ])
    ```
    Is not an array of array. 
It's 2 parameters ; each one of type array.
Have a look here : https://www.starknetjs.com/docs/guides/interact#light-and-fast-call

**Comment by tabaktoni** [comment]
call's second parameter is ArgsOrCalldata, which is an Array of raw Arguments or compiled Calldata.
So the usage would be:
```ts
await myTestContract.call("method", [argument]);
```
In this case
```ts
await myTestContract.call("array2d_array", [
  [[1n, 2n],[3n, 4n]], // one argument that is 2d array
]);
```
