### ISSUE TITLE
I encountered an issue when using account.execute to access multiple contracts in a single transaction.

### ISSUE THREAD

**Issue by JueShanCoder** [0xs34n/starknet.js#691]
- Below is my code snippet:
 ```typescript
 export async function swapETH2USDC(provider: Provider, account: Account, ethAmount: BigNumberish) {
    const starkGateETH = await getStarkERC20Contract(provider, ETH_ADDRESS);
    const eth = await starkGateETH.balanceOf(account.address);
    const ethBalance = uint256.uint256ToBN(eth.balance);
    // const multiCall = await account.getNonce().then(nonce => {
        const multiCall = await account.execute([
            // call starkGate eth contract to approve.
            {
                contractAddress: ETH_ADDRESS,
                entrypoint: "approve",
                calldata: CallData.compile({
                    spender: tenKAddrs.AMM_ROUTER,
                    amount: uint256.bnToUint256(ethAmount)
                })
            },
            
            // call 10kswap ETHUSDC contract to swap.
            {
                contractAddress: tenKAddrs.AMM_ROUTER,
                entrypoint: "swapExactTokensForTokens",
                calldata: CallData.compile({
                    amountIn: uint256.bnToUint256(ethAmount),
                    amountOutMin: uint256.bnToUint256(0),
                    path_len: 2,
                    path: [
                        ETH_ADDRESS,
                        USDC_ADDRESS
                    ],
                    to: account.address,
                    deadline: getCurrentTimestamp()
                })
            }
        ],
        // undefined,
        // { maxFee: "60240850062409", nonce: nonce},
        );
    // });
    const tx = multiCall.transaction_hash;
    await provider.waitForTransaction(tx);
    console.log(`[10k swapETH2USDC] tx: ${tx}`);
}
 ```
- The error I encountered is:
```shell
LibraryError: -32603: Internal error: StarknetErrorCode.TRANSACTION_FAILED: Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:228)
Unknown location (pc=0:214)

Error in the called contract (0x47fceebf138811dd7ef33b9aa81dd0bed04157f40531bf41b403d1b48669cbb):
Error at pc=0:219:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:8090)
Unknown location (pc=0:8038)
Unknown location (pc=0:5734)
Unknown location (pc=0:5771)
Unknown location (pc=0:5755)

Error in the called contract (0x7a6f98c03379b9513ca84cca1373ff452a7462a3b61598f0af5bb27ad7f76d1):
Error at pc=0:2170:
An ASSERT_EQ instruction failed: 11:9 != 11:10.
    at RpcProvider.errorHandler (/Users/liuzilin/code/rich-club/Startknet/node_modules/starknet/dist/index.js:4077:13)
    at RpcProvider.fetchEndpoint (/Users/liuzilin/code/rich-club/Startknet/node_modules/starknet/dist/index.js:4084:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Account.estimateInvokeFee (/Users/liuzilin/code/rich-club/Startknet/node_modules/starknet/dist/index.js:5612:22)
    at async Account.getSuggestedMaxFee (/Users/liuzilin/code/rich-club/Startknet/node_modules/starknet/dist/index.js:5913:23)
    at async Account.execute (/Users/liuzilin/code/rich-club/Startknet/node_modules/starknet/dist/index.js:5717:49)
    at async swapETH2USDC (/Users/liuzilin/code/rich-club/Startknet/dist/src/dex/10kswap/swap.js:18:23)
    at async start10kSwap (/Users/liuzilin/code/rich-club/Startknet/dist/src/example/10kswap.js:17:9)
```

**I would appreciate your help and guidance on this issue.**

**Comment by JueShanCoder** [comment]
Use starknet js version is ^5.14.1 .

**Comment by JueShanCoder** [comment]
![image](https://github.com/0xs34n/starknet.js/assets/67142106/862ed30d-bf81-4317-b1f7-9cca822c344c)

- the transaction rejected
```shell
Transaction from sender address 0x47fceebf138811dd7ef33b9aa81dd0bed04157f40531bf41b403d1b48669cbb has failed.
ExecutionError(VirtualMachineExecutionErrorWithTrace { trace: "Error in the called contract (0x047fceebf138811dd7ef33b9aa81dd0bed04157f40531bf41b403d1b48669cbb):\nError at pc=0:10:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:228)\nUnknown location (pc=0:214)\n\nError in the called contract (0x047fceebf138811dd7ef33b9aa81dd0bed04157f40531bf41b403d1b48669cbb):\nError at pc=0:219:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:8090)\nUnknown location (pc=0:8038)\nUnknown location (pc=0:5734)\nUnknown location (pc=0:5755)\n\nError in the called contract (0x07a6f98c03379b9513ca84cca1373ff452a7462a3b61598f0af5bb27ad7f76d1):\nError at pc=0:2170:\nAn ASSERT_EQ instruction failed: 6:7 != 6:10.", source: CairoRunError(VmException(VmException { pc: 10, inst_location: None, inner_exc: Hint((0, CustomHint("Error in the called contract (0x047fceebf138811dd7ef33b9aa81dd0bed04157f40531bf41b403d1b48669cbb):\nError at pc=0:219:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:8090)\nUnknown location (pc=0:8038)\nUnknown location (pc=0:5734)\nUnknown location (pc=0:5755)\n\nError in the called contract (0x07a6f98c03379b9513ca84cca1373ff452a7462a3b61598f0af5bb27ad7f76d1):\nError at pc=0:2170:\nAn ASSERT_EQ instruction failed: 6:7 != 6:10."))), error_attr_value: None, traceback: Some("Cairo traceback (most recent call last):\nUnknown location (pc=0:228)\nUnknown location (pc=0:214)\n") })) })
```

**Comment by JueShanCoder** [comment]
@tabaktoni  I changed the deadline + 5 minutes according to your method, still the same error.

**Comment by JueShanCoder** [comment]
![image](https://github.com/0xs34n/starknet.js/assets/67142106/fb8cbeb5-9e60-4b4b-b492-719859767e26)

Already solved, I missed this..
